# Generated by Django 5.0.3 on 2024-04-23 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banking_app', '0004_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='account_id',
            new_name='account',
        ),
    ]
